// Экспортируем все хранилища из одной точки для удобства использования
export { useAuthStore } from './modules/auth/auth'
export { useAuthUiStore } from './modules/auth/authUi'
export { useAuthorsStore } from './modules/authors/authors'
export { useAuthorsUiStore } from './modules/authors/authorsUi'
export { useBooksStore } from './modules/books/books'
export { useBooksUiStore } from './modules/books/booksUi'
export { useCartStore } from './modules/cart/cart'
export { useOrdersStore } from './modules/orders/orders'
export { useOrdersUiStore } from './modules/orders/ordersUi'
export { useUiStore } from './modules/ui/ui'
export { useUsersStore } from './modules/users/users'
export { useUsersUiStore } from './modules/users/usersUi'
